# syntax = docker/dockerfile:1
FROM registry.nearbycomputing.com/nbycomp/base/golang:1.24.6-alpine as builder

RUN apk add -U yq bash sed && \
    go install github.com/deepmap/oapi-codegen/v2/cmd/oapi-codegen@v2.2.0
ENTRYPOINT ["/api/apigen.sh"]
